### ISSUE TITLE
Failed to build Chromium

### ISSUE THREAD

**Issue by AndyChung1997** [open-quantum-safe/oqs-demos#93] opened 2021-07-14 10:10 UTC
Hi, I'm trying to build Chromium using the [oqs-demos/chromium](https://github.com/open-quantum-safe/oqs-demos/tree/main/chromium).  The first few steps are executed successfully. But when I type `autoninja -C out/Default chrome` to build Chromium, I get an error message.   
Just like:

```
FAILED: obj/third_party/boringssl/boringssl/p_oqs.o
../../third_party/boringssl/src/crypto/evp/p_oqs.c:19:10: fatal error: 'oqs/oqs.h' file not found
#include <oqs/oqs.h>
         ^~~~~~~~~~~
1 error generated.
...
FAILED: obj/third_party/boringssl/boringssl/p_oqs_asn1.o
...
../../third_party/boringssl/src/crypto/evp/p_oqs_asn1.c:20:10: fatal error: 'oqs/oqs.h' file not found
...
ninja: build stopped: subcommand failed.
```
How can I fix it? Thank you for your help!!

**Comment by baentsch** [comment] 2021-07-14 12:34
Hi, this looks like `liboqs` did not get properly installed: Please check step 4 of [the instructions](https://github.com/open-quantum-safe/oqs-demos/tree/main/chromium) carefully: maybe you did not set "<CHROMIUM_ROOT>" correctly for your setting? Maybe try running `find . -name oqs.h` to check the whereabouts of this OQS key include file in your chromium source tree.

**Comment by taylormadehdz** [comment] 2021-07-15 16:59
Hi we are getting a similar issue. We built liboqs successfully (as evident by the tests) and we noticed that the oqs folder is located in `include` folder of `liboqs/build` as well as `liboqs.a` inside `liboqs/lib`. Here is a picture of the paths: 

<img width="1440" alt="Screen Shot 2021-07-15 at 9 53 27 AM" src="https://user-images.githubusercontent.com/36052099/125827655-6b3ee57e-6722-439e-8b19-380c71253084.png">

Issue: when we go onto building by running `autoninja -C out/Default chrome` we get the following error: 

```
admin1@dcs-quantum:~/chromium/src$ autoninja -C out/Default chrome
ninja: Entering directory `out/Default'
ninja: error: '../../third_party/boringssl/src/oqs/lib/liboqs.a', needed by 'obj/base/libbase.a', missing and no known rule to make it

```
Could I just move around the liboqs?

**Comment by taylormadehdz** [comment] 2021-07-15 17:15
@baentsch  i guess the better question is, since moving around did seem to work until i just ran into another issue: 
<img width="1435" alt="Screen Shot 2021-07-15 at 10 14 22 AM" src="https://user-images.githubusercontent.com/36052099/125829560-33a7f5af-97b5-456f-9eb7-fddaab1638d8.png">
 Where should I have put this build directory in order for me to successfully execute `autoninja -C out/Default chrome`

**Comment by taylormadehdz** [comment] 2021-07-15 19:29
@AndyChung1997  i am successfully building now and i re applied the oqs-mods patch. when you applied oqs-mods patch was it successful? I did some git force commands so hopefully all is correct but i was getting the error you mentioned above which seems to have gone away...

**Comment by taylormadehdz** [comment] 2021-07-15 21:23
@baentsch there is an issue with applying the patch it keeps saying the file is corrupt if you have any guidance on this

**Comment by baentsch** [comment] 2021-07-15 21:56
Please share the steps that would allow reproduction of the issue (incl. trace of error message, ideally). Thanks.

**Comment by AndyChung1997** [comment] 2021-07-16 06:23
> @AndyChung1997 i am successfully building now and i re applied the oqs-mods patch. when you applied oqs-mods patch was it successful? I did some git force commands so hopefully all is correct but i was getting the error you mentioned above which seems to have gone away...

Yes,  I am successfully building now. I forgot to apply oqs-mods.patch last time. Thank you for your suggestion.

**Comment by AndyChung1997** [comment] 2021-07-16 06:46
> Hi, this looks like `liboqs` did not get properly installed: Please check step 4 of [the instructions](https://github.com/open-quantum-safe/oqs-demos/tree/main/chromium) carefully: maybe you did not set "<CHROMIUM_ROOT>" correctly for your setting? Maybe try running `find . -name oqs.h` to check the whereabouts of this OQS key include file in your chromium source tree.

Thank you. I forgot to apply oqs-mods.patch last time.  Now, my Chromium can work successfully. 😄

**Comment by AndyChung1997** [comment] 2021-07-16 08:35
@baentsch Hi, I want to verify that Chromium can perform a TLS 1.3 handshake using a post-quantum key-exchange. I navigate to the `<CHROMIUM_ROOT>/third_party/boringssl/src` folder, and build OQS-BoringSSL by running `mkdir build && cd build && cmake -GNinja ..` .   Then the CLI shows `No package 'libunwind-generic' found` . Here is a picture of error message : 

<img width="728" alt="擷取" src="https://user-images.githubusercontent.com/56081724/125917034-e6f2b35e-2c61-4bfe-9dd9-7588a1afd211.PNG">

Will it cause an error in the next step if I ignore this error message?

Then, in the build directory, I run `./tool/bssl server -accept 4433 -www -loop -curves kyber512` . It tells me there is no such directory. Here is a picture of error message : 

<img width="737" alt="擷取2" src="https://user-images.githubusercontent.com/56081724/125918039-77a618eb-99af-40c8-98bb-e53f50315b8b.PNG">

The previous instructions are executed successfully. How can I fix this issue?

**Comment by baentsch** [comment] 2021-07-16 10:26
> Will it cause an error in the next step if I ignore this error message?

This library `unwind` does not ring a bell to me. So you could try to continue without it (but you could also try to install it: What about running `apt install libunwind-dev`?). What you should do at the end of building `oqs-boringssl` is test it: run `python3 oqs_scripts/try_handshake.py` in the "<CHROMIUM_ROOT>/third_party/boringssl/src" folder: If you see a "Connected" in the output, that part works OK. 

To the next question: If `./tool/bssl` does not exist, the `oqs-boringssl` build failed for sure. Did you run `ninja` at all? Or did you only run `cmake`?

**Comment by baentsch** [comment] 2021-07-16 10:32
Wow - I just see in our build instructions that the actual build command (`ninja`) is missing: I think, the full command should be `mkdir build && cd build && cmake -GNinja .. && ninja`. @xvzcf Do you agree? The main Chromium build does not take care of that, right?

**Comment by AndyChung1997** [comment] 2021-07-17 11:02
> > Will it cause an error in the next step if I ignore this error message?
> 
> This library `unwind` does not ring a bell to me. So you could try to continue without it (but you could also try to install it: What about running `apt install libunwind-dev`?). What you should do at the end of building `oqs-boringssl` is test it: run `python3 oqs_scripts/try_handshake.py` in the "<CHROMIUM_ROOT>/third_party/boringssl/src" folder: If you see a "Connected" in the output, that part works OK.
> 
> To the next question: If `./tool/bssl` does not exist, the `oqs-boringssl` build failed for sure. Did you run `ninja` at all? Or did you only run `cmake`?

I ran `ninja` , and `./tool/bssl` exists. When I used the newly built Chromium to access the OQS test server, the error message said `NO_SHARED_GROUP` . Here is a picture of error message :

<img width="733" alt="擷取" src="https://user-images.githubusercontent.com/56081724/126034838-70b03b34-2023-425f-ab52-ae47e006d31f.PNG">
<img width="743" alt="2" src="https://user-images.githubusercontent.com/56081724/126034848-8b13a1af-aa33-4527-b426-7fe9e0dd9d8c.PNG">

Did I miss some steps?

**Comment by baentsch** [comment] 2021-07-17 11:21
"NO_SHARED_GROUP" means exactly that: Server and client have no KEM algorithms (TLS1.3 groups) in common: You started the test server with "group" (or "curve" in the old terminology) `kyber512` while Chromium only supports a small subset as [per the documentation](https://github.com/open-quantum-safe/oqs-demos/tree/main/chromium): Only [these](https://github.com/open-quantum-safe/boringssl/blob/master/ssl/t1_lib.cc#L375) work --> Try starting `bssl` with group "p256_kyber90s512".

**Comment by AndyChung1997** [comment] 2021-07-25 15:41
> "NO_SHARED_GROUP" means exactly that: Server and client have no KEM algorithms (TLS1.3 groups) in common: You started the test server with "group" (or "curve" in the old terminology) `kyber512` while Chromium only supports a small subset as [per the documentation](https://github.com/open-quantum-safe/oqs-demos/tree/main/chromium): Only [these](https://github.com/open-quantum-safe/boringssl/blob/master/ssl/t1_lib.cc#L375) work --> Try starting `bssl` for example with group "p256_kyber90s512" and it should work.

@baentsch It can work. Thank you for your help. 😄

**Comment by baentsch** [comment] 2021-07-28 09:12
UW. Closing issue accordingly.

**Closed by baentsch** 2021-07-28 09:12 UTC
