### ISSUE TITLE
Wireshark docker image does not recognize PQC algorithm: Display as Unknown

### ISSUE THREAD

**Issue by Jpgig** [open-quantum-safe/oqs-demos#164] opened 2022-11-09 13:22 UTC
I have downloaded the Docker Wireshark image as noted on the code page and ran it as per the instructions
I can see the Wireshark version as Version 3.4.9 (Git commit 365e236f5efe) 

I captured the Wireshark traffic but still, it does not recognize the post-quantum crypto algorithm in the handshake process.
![image](https://user-images.githubusercontent.com/115164852/200841197-f8289e97-483e-4419-b6dc-ce7db669caaa.png)

**Comment by anhu** [comment] 2022-11-10 17:50
These are for signature algorithms.  When I first did this wireshark modification, we didn't yet support signature schemes and so I did not think to make the modification for them.  

@Jpgig , as a workaround, you can use the oqs style names.  I think those should be populated.

**Comment by Jpgig** [comment] 2022-11-15 14:30
Hi Anthony, I also used oqs style names but still, it does not populate the PQC  algo name. Can you suggest any other place where I can look for the changes?

**Comment by anhu** [comment] 2022-11-15 14:51
hi @Jpgig , I'll have to look into this more deeper. You'll have to give me a bit of time as I'm currently looking into other matters. 
Please check for updates by end of next week. 
Warm regards, Anthony

**Comment by anhu** [comment] 2022-11-21 17:09
Hi @Jpgig , 

I just check and noticed that I had not updated for Dilithium as when we did this integration, we did not yet support Dilithium.   Please see  https://github.com/open-quantum-safe/oqs-demos/pull/170 which updates our integration.

**Comment by anhu** [comment] 2022-11-22 21:52
@Jpgig , 

Please try again. I've made sure it works: 

![image](https://user-images.githubusercontent.com/1266573/203428592-7a21753d-c4f6-4208-9bfe-dea3ab2ec60e.png)

If docker doesn't seem to work, try using build.sh.  Make sure to change the flavour at the top. 

Warm regards, Anthony

**Comment by anhu** [comment] 2022-11-23 17:08
to try the build.sh: 

cd oqs-demos/wireshark
git fetch 
git checkout origin/wireshark_wolf_dilithium
# edit build.sh to change to wolfssl flavor
./build.sh
# enter your sudo password
# you might have problems with software that needs to be install.... resolve them. 
cd wireshark-3.4.9/build 
sudo ./run/wireshark &
# enter your sudo password
```
You should know what to do now is specific to your situation. 

Warm regards, Anthony

**Comment by Jpgig** [comment] 2022-11-29 14:39
Thanks, Anthony
I used all updated files but still it doe not identify the Signature algorithm in Wireshark.
Please find below a screen shot of the Wireshark.
![image](https://user-images.githubusercontent.com/115164852/204558270-49cace32-15fd-43b7-924d-d1e945398ad2.png)

**Comment by anhu** [comment] 2022-11-29 14:54
Hi @Jpgig , 

Unfortunately, I cannot reproduce what you are seeing.  (See my screenshot above.).  My only suggestion now would be to go through the build.sh file and run each command step by step to see which command is going wrong for you on your particular system. 

Warm regards, Anthony

**Comment by anhu** [comment] 2022-11-30 14:48
@Jpgig , you expressed that you found success over a private channel.  Can you do so publicly here as well?  Also, please close the issue if you feel it has been resolved.

**Comment by anhu** [comment] 2022-11-30 14:50
@Jpgig , please also comment on https://github.com/open-quantum-safe/oqs-demos/pull/170 .

**Closed** 2022-12-05 16:55 UTC

**Comment by baentsch** [comment] 2022-12-06 06:06
@Jpgig FWIW, the main OQS image [openquantumsafe/wireshark](https://hub.docker.com/repository/docker/openquantumsafe/wireshark) should now also work OK for you.
