### ISSUE TITLE
Issue With OQS-Chromium

### ISSUE THREAD

**Issue by Raytonne** [open-quantum-safe/oqs-demos#111] opened 2021-12-31 22:46 UTC
Hello,

I've already contacted @baentsch regarding this issue, and it might be helpful to post it.

Here is the problem: we've created the following certificate chain:

Common Name | Summary | Public Key Algorithm | Signature Algorithm | Link
:---: | :---: | :---: | :---: | ---
TestCA | Root Certificate | P-384 | ecdsa-with-SHA384 | [view](https://pastebin.com/raw/jAj05vTW)
Test TLS CA | Intermediate Certificate | dilithium2 | ecdsa-with-SHA384 | [view](https://pastebin.com/raw/WETU1aCZ)
dilithium2.webhop.me | Leaf Certificate | dilithium2 | dilithium2 | [view](https://pastebin.com/raw/c1auZzC1)

The root certificate has been imported into Chromium successfully. The website [https://dilithium2.webhop.me (IPv6 Only)](https://dilithium2.webhop.me/) supports `frodo640aes:ntru_hps2048509:bikel1:hqc128:p256_lightsaber:p256_sikep434:p256_sidhp434` key exchange algorithms and is accessible (we checked with OQS-cURL). 

**What We Expect:**
Since the root certificate has been installed and the verification of _root certificate - intermediate certificate_ chain doesn't require any OQS-enabled library, the website should be accessible in Chromium.

**What Actually Happened:**
Chromium returned two errors:

> [10842:10862:1231/225648.339848:ERROR:ssl_client_socket_impl.cc(959)] handshake failed; returned -1, SSL error code 1, net_error -113
>[10842:10862:1231/225648.343227:ERROR:ssl_client_socket_impl.cc(959)] handshake failed; returned -1, SSL error code 1, net_error -207

![Chromium Screenshot 1](https://i.ibb.co/Pg03cHY/OQS2021Q.jpg)

We further found that Chromium failed to verify the _root certificate - intermediate certificate_ chain, but it succeeded in verifying the _intermediate certificate - leaf certificate_ chain.

![Chromium Screenshot 2](https://i.ibb.co/vV9rq1m/OQS2021W.jpg)

We tried to add the intermediate certificate to Chromium; nonetheless, we got the same error as #92.

Any ideas why this happened?

p.s. Wish everyone a joyful New Year! :relaxed:

**Comment by baentsch** [comment] 2022-01-01 10:24
Thanks for the test and the complete description of your setup! Based on this, two questions:

> Since the root certificate has been installed and the verification of root certificate - intermediate certificate chain doesn't require any OQS-enabled library, the website should be accessible in Chromium.

Why are you expecting this? Chromium ought to verify the whole cert chain, incl. the dilithium-site cert and not just the "last step". Hence #92 (and the errors shown) are to be expected, as there is a QSC alg involved, right?

> We further found that Chromium failed to verify the root certificate - intermediate certificate chain, but it succeeded in verifying the intermediate certificate - leaf certificate chain.

How did you come to this conclusion/what test did you do? I would actually expect the exact opposite: The intermediate cert could/should be verifiable with classic crypto while the site/leaf->intermediate cert needing QSC should not be as per #92.

**Comment by Raytonne** [comment] 2022-01-01 12:00
> The intermediate cert could/should be verifiable with classic crypto while the site/leaf->intermediate cert needing QSC should not be as per #92.

I've thought about this reason. What is really confusing is that there is no root certificate in the Chromium Certificate Viewer hierarchy. I initially thought this was due to I didn't supply the root certificate in the certificate chain, so I modified nginx server config and added the root certificate in the certificate chain and the root certificate still didn't appear in the Certificate Viewer hierarchy.

If this is the reason, why Chromium Certificate Viewer shows the intermediate certificate? Both intermediate certificate and root certificate shouldn't appear in the Certificate Viewer hierarchy as the chain already broke at _leaf - intermediate_.

**Comment by baentsch** [comment] 2022-01-01 17:04
> If this is the reason, why Chromium Certificate Viewer shows the intermediate certificate?

I don't know this -- probably one would need to go through the cert verification logic of Chromium (nss) to really understand what's going on. Personally I didn't get around to looking into `libnss` to be able to give a good answer.

**Comment by Raytonne** [comment] 2022-01-04 23:06
Good suggestion.

**Comment by baentsch** [comment] 2022-01-05 15:38
As it seems this issue indeed is caused by `libnss` not being QSC-enabled we'll close this issue referring to #92 for further discussions/activity. Please feel free to re-open this with further feedback if you don't think likewise, @Raytonne. Thanks again for your test & report!

**Closed by baentsch** 2022-01-05 15:38 UTC
